import os
import sys
import oracledb

def apply_schema():
    # Credentials from environment
    user = os.getenv('ORACLE_DB_USER', 'system')
    password = os.getenv('ORACLE_DB_PASSWORD', 'oracle')
    host = os.getenv('ORACLE_DB_HOST', 'oracle')
    port = os.getenv('ORACLE_DB_PORT', '1521')
    name = os.getenv('ORACLE_DB_NAME', 'xepdb1')
    dsn = f"//{host}:{port}/{name}"

    try:
        conn = oracledb.connect(user=user, password=password, dsn=dsn)
        cursor = conn.cursor()
        print(f"Connected to Oracle at {dsn}")
        
        # 1. Helper to check if table exists
        def table_exists(table_name):
            cursor.execute("SELECT count(*) FROM user_tables WHERE table_name = :1", [table_name.upper()])
            return cursor.fetchone()[0] > 0
        
        # 2. Drop tables that need timezone fix (safest approach)
        print("Dropping tables with incorrect timezone configuration...")
        tables_to_drop = ['django_admin_log', 'django_session', 'announcements', 'answers', 
                         'questions', 'submissions', 'assignments', 'lesson_files', 'lessons',
                         'enrollments', 'classes', 'users_user_permissions', 'users_groups',
                         'users', 'auth_group_permissions', 'auth_group', 'auth_permission',
                         'django_content_type', 'django_migrations']
        
        for tbl in tables_to_drop:
            if table_exists(tbl):
                try:
                    cursor.execute(f'DROP TABLE {tbl} CASCADE CONSTRAINTS')
                    print(f"Dropped {tbl}")
                except Exception as e:
                    print(f"Could not drop {tbl}: {e}")

        # 3. Table definitions - using TIMESTAMP instead of TIMESTAMP WITH TIME ZONE
        tables = [
            ("django_migrations", """
                CREATE TABLE django_migrations (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    app VARCHAR2(255) NOT NULL,
                    name VARCHAR2(255) NOT NULL,
                    applied TIMESTAMP NOT NULL
                )
            """),
            ("django_content_type", """
                CREATE TABLE django_content_type (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(100),
                    app_label VARCHAR2(100) NOT NULL,
                    model VARCHAR2(100) NOT NULL,
                    CONSTRAINT uk_ct_label_model UNIQUE (app_label, model)
                )
            """),
            ("auth_permission", """
                CREATE TABLE auth_permission (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(255) NOT NULL,
                    content_type_id NUMBER NOT NULL,
                    codename VARCHAR2(100) NOT NULL,
                    CONSTRAINT fk_perm_ct FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) ON DELETE CASCADE,
                    CONSTRAINT uk_perm_ct_code UNIQUE (content_type_id, codename)
                )
            """),
            ("auth_group", """
                CREATE TABLE auth_group (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(150) UNIQUE NOT NULL
                )
            """),
            ("auth_group_permissions", """
                CREATE TABLE auth_group_permissions (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    group_id NUMBER NOT NULL,
                    permission_id NUMBER NOT NULL,
                    CONSTRAINT fk_gp_group FOREIGN KEY (group_id) REFERENCES auth_group(id) ON DELETE CASCADE,
                    CONSTRAINT fk_gp_perm FOREIGN KEY (permission_id) REFERENCES auth_permission(id) ON DELETE CASCADE,
                    CONSTRAINT uk_gp_group_perm UNIQUE (group_id, permission_id)
                )
            """),
            ("users", """
                CREATE TABLE users (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    password VARCHAR2(128) NOT NULL,
                    last_login TIMESTAMP,
                    is_superuser NUMBER(1) DEFAULT 0 NOT NULL,
                    username VARCHAR2(150) UNIQUE NOT NULL,
                    first_name VARCHAR2(150),
                    last_name VARCHAR2(150),
                    email VARCHAR2(254),
                    is_staff NUMBER(1) DEFAULT 0 NOT NULL,
                    is_active NUMBER(1) DEFAULT 1 NOT NULL,
                    date_joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    role VARCHAR2(10) NOT NULL,
                    bio CLOB,
                    avatar VARCHAR2(100),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                )
            """),
            ("users_groups", """
                CREATE TABLE users_groups (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id NUMBER NOT NULL,
                    group_id NUMBER NOT NULL,
                    CONSTRAINT fk_ug_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                    CONSTRAINT fk_ug_group FOREIGN KEY (group_id) REFERENCES auth_group(id) ON DELETE CASCADE,
                    CONSTRAINT uk_ug_user_group UNIQUE (user_id, group_id)
                )
            """),
            ("users_user_permissions", """
                CREATE TABLE users_user_permissions (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id NUMBER NOT NULL,
                    permission_id NUMBER NOT NULL,
                    CONSTRAINT fk_uup_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                    CONSTRAINT fk_uup_perm FOREIGN KEY (permission_id) REFERENCES auth_permission(id) ON DELETE CASCADE,
                    CONSTRAINT uk_uup_user_perm UNIQUE (user_id, permission_id)
                )
            """),
            ("classes", """
                CREATE TABLE classes (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(200) NOT NULL,
                    description CLOB,
                    class_code VARCHAR2(10) UNIQUE NOT NULL,
                    subject VARCHAR2(100),
                    room VARCHAR2(50),
                    is_active NUMBER(1) DEFAULT 1 NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    teacher_id NUMBER NOT NULL,
                    CONSTRAINT fk_classes_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE
                )
            """),
            ("enrollments", """
                CREATE TABLE enrollments (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    is_active NUMBER(1) DEFAULT 1 NOT NULL,
                    class_enrolled_id NUMBER NOT NULL,
                    student_id NUMBER NOT NULL,
                    CONSTRAINT fk_enroll_class FOREIGN KEY (class_enrolled_id) REFERENCES classes(id) ON DELETE CASCADE,
                    CONSTRAINT fk_enroll_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
                    CONSTRAINT uk_enroll_student_class UNIQUE (student_id, class_enrolled_id)
                )
            """),
            ("lessons", """
                CREATE TABLE lessons (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR2(200) NOT NULL,
                    description CLOB NOT NULL,
                    "ORDER" NUMBER DEFAULT 0 NOT NULL,
                    is_published NUMBER(1) DEFAULT 1 NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    class_lesson_id NUMBER NOT NULL,
                    CONSTRAINT fk_lesson_class FOREIGN KEY (class_lesson_id) REFERENCES classes(id) ON DELETE CASCADE
                )
            """),
            ("lesson_files", """
                CREATE TABLE lesson_files (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "FILE" VARCHAR2(100) NOT NULL,
                    file_name VARCHAR2(255) NOT NULL,
                    file_size NUMBER NOT NULL,
                    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    lesson_id NUMBER NOT NULL,
                    CONSTRAINT fk_file_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE
                )
            """),
            ("assignments", """
                CREATE TABLE assignments (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR2(200) NOT NULL,
                    description CLOB NOT NULL,
                    due_date TIMESTAMP NOT NULL,
                    max_points NUMBER DEFAULT 100 NOT NULL,
                    allow_late_submission NUMBER(1) DEFAULT 1 NOT NULL,
                    is_published NUMBER(1) DEFAULT 1 NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    class_assignment_id NUMBER NOT NULL,
                    CONSTRAINT fk_assign_class FOREIGN KEY (class_assignment_id) REFERENCES classes(id) ON DELETE CASCADE
                )
            """),
            ("submissions", """
                CREATE TABLE submissions (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "FILE" VARCHAR2(100) NOT NULL,
                    file_name VARCHAR2(255) NOT NULL,
                    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    status VARCHAR2(10) NOT NULL,
                    points NUMBER,
                    feedback CLOB,
                    assignment_id NUMBER NOT NULL,
                    student_id NUMBER NOT NULL,
                    CONSTRAINT fk_sub_assign FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE CASCADE,
                    CONSTRAINT fk_sub_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
                    CONSTRAINT uk_sub_student_assign UNIQUE (assignment_id, student_id)
                )
            """),
            ("questions", """
                CREATE TABLE questions (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    question_text CLOB NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    lesson_id NUMBER NOT NULL,
                    student_id NUMBER NOT NULL,
                    CONSTRAINT fk_ques_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE,
                    CONSTRAINT fk_ques_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
                )
            """),
            ("answers", """
                CREATE TABLE answers (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    answer_text CLOB NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    question_id NUMBER UNIQUE NOT NULL,
                    teacher_id NUMBER NOT NULL,
                    CONSTRAINT fk_ans_ques FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
                    CONSTRAINT fk_ans_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE
                )
            """),
            ("announcements", """
                CREATE TABLE announcements (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR2(200) NOT NULL,
                    content CLOB NOT NULL,
                    is_pinned NUMBER(1) DEFAULT 0 NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    class_announcement_id NUMBER NOT NULL,
                    teacher_id NUMBER NOT NULL,
                    CONSTRAINT fk_ann_class FOREIGN KEY (class_announcement_id) REFERENCES classes(id) ON DELETE CASCADE,
                    CONSTRAINT fk_ann_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE
                )
            """),
            ("django_session", """
                CREATE TABLE django_session (
                    session_key VARCHAR2(40) PRIMARY KEY,
                    session_data CLOB NOT NULL,
                    expire_date TIMESTAMP NOT NULL
                )
            """),
            ("django_admin_log", """
                CREATE TABLE django_admin_log (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    action_time TIMESTAMP NOT NULL,
                    object_id CLOB,
                    object_repr VARCHAR2(200) NOT NULL,
                    action_flag NUMBER(2) NOT NULL,
                    change_message CLOB NOT NULL,
                    content_type_id NUMBER,
                    user_id NUMBER NOT NULL,
                    CONSTRAINT fk_admin_log_ct FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) ON DELETE SET NULL,
                    CONSTRAINT fk_admin_log_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                )
            """)
        ]

        # 4. Create tables one by one
        for name, sql in tables:
            print(f"Creating table {name}...")
            try:
                cursor.execute(sql)
                print(f"✓ Table {name} created.")
            except Exception as e:
                print(f"✗ Error creating table {name}: {e}")
                # Continue anyway to see other errors

        # 5. Inject metadata
        print("Registering migrations...")
        
        migration_values = [
            ('contenttypes', '0001_initial'),
            ('contenttypes', '0002_remove_content_type_name'),
            ('auth', '0001_initial'),
            ('auth', '0012_alter_user_first_name_max_length'),
            ('core', '0001_initial'),
            ('admin', '0001_initial'),
            ('sessions', '0001_initial')
        ]
        
        for app, mname in migration_values:
            cursor.execute("INSERT INTO django_migrations (app, name, applied) VALUES (:1, :2, CURRENT_TIMESTAMP)", [app, mname])
        
        conn.commit()
        print("\n✓ Schema and migrations finalized successfully!")

    except Exception as e:
        print(f"\n✗ Critical error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    finally:
        if 'conn' in locals():
            conn.close()

if __name__ == "__main__":
    apply_schema()
