import os
import sys

def apply_schema():
    import oracledb


    # Embedded PL/SQL schema
    SCHEMA_SQL = """
DECLARE
    v_count NUMBER;
BEGIN
    -- 1. Django Internal Tables
    
    -- django_migrations
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'DJANGO_MIGRATIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE django_migrations (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            app VARCHAR2(255) NOT NULL,
            name VARCHAR2(255) NOT NULL,
            applied TIMESTAMP WITH TIME ZONE NOT NULL
        )';
    END IF;

    -- django_content_type
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'DJANGO_CONTENT_TYPE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE django_content_type (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(100),
            app_label VARCHAR2(100) NOT NULL,
            model VARCHAR2(100) NOT NULL,
            CONSTRAINT uk_ct_label_model UNIQUE (app_label, model)
        )';
    END IF;

    -- auth_permission
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'AUTH_PERMISSION';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE auth_permission (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(255) NOT NULL,
            content_type_id NUMBER NOT NULL,
            codename VARCHAR2(100) NOT NULL,
            CONSTRAINT fk_perm_ct FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) ON DELETE CASCADE,
            CONSTRAINT uk_perm_ct_code UNIQUE (content_type_id, codename)
        )';
    END IF;

    -- auth_group
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'AUTH_GROUP';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE auth_group (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(150) UNIQUE NOT NULL
        )';
    END IF;

    -- auth_group_permissions
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'AUTH_GROUP_PERMISSIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE auth_group_permissions (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_id NUMBER NOT NULL,
            permission_id NUMBER NOT NULL,
            CONSTRAINT fk_gp_group FOREIGN KEY (group_id) REFERENCES auth_group(id) ON DELETE CASCADE,
            CONSTRAINT fk_gp_perm FOREIGN KEY (permission_id) REFERENCES auth_permission(id) ON DELETE CASCADE,
            CONSTRAINT uk_gp_group_perm UNIQUE (group_id, permission_id)
        )';
    END IF;

    -- 2. Application Tables (Core App)

    -- users
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'USERS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE users (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            password VARCHAR2(128) NOT NULL,
            last_login TIMESTAMP WITH TIME ZONE,
            is_superuser NUMBER(1) DEFAULT 0 NOT NULL,
            username VARCHAR2(150) UNIQUE NOT NULL,
            first_name VARCHAR2(150),
            last_name VARCHAR2(150),
            email VARCHAR2(254),
            is_staff NUMBER(1) DEFAULT 0 NOT NULL,
            is_active NUMBER(1) DEFAULT 1 NOT NULL,
            date_joined TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            role VARCHAR2(10) NOT NULL,
            bio CLOB,
            avatar VARCHAR2(100),
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
        )';
    END IF;

    -- users_groups (M2M)
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'USERS_GROUPS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE users_groups (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id NUMBER NOT NULL,
            group_id NUMBER NOT NULL,
            CONSTRAINT fk_ug_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            CONSTRAINT fk_ug_group FOREIGN KEY (group_id) REFERENCES auth_group(id) ON DELETE CASCADE,
            CONSTRAINT uk_ug_user_group UNIQUE (user_id, group_id)
        )';
    END IF;

    -- users_user_permissions (M2M)
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'USERS_USER_PERMISSIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE users_user_permissions (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id NUMBER NOT NULL,
            permission_id NUMBER NOT NULL,
            CONSTRAINT fk_uup_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            CONSTRAINT fk_uup_perm FOREIGN KEY (permission_id) REFERENCES auth_permission(id) ON DELETE CASCADE,
            CONSTRAINT uk_uup_user_perm UNIQUE (user_id, permission_id)
        )';
    END IF;

    -- classes
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'CLASSES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE classes (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(200) NOT NULL,
            description CLOB,
            class_code VARCHAR2(10) UNIQUE NOT NULL,
            subject VARCHAR2(100),
            room VARCHAR2(50),
            is_active NUMBER(1) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            teacher_id NUMBER NOT NULL,
            CONSTRAINT fk_classes_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE
        )';
    END IF;

    -- enrollments
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'ENROLLMENTS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE enrollments (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            is_active NUMBER(1) DEFAULT 1 NOT NULL,
            class_enrolled_id NUMBER NOT NULL,
            student_id NUMBER NOT NULL,
            CONSTRAINT fk_enroll_class FOREIGN KEY (class_enrolled_id) REFERENCES classes(id) ON DELETE CASCADE,
            CONSTRAINT fk_enroll_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
            CONSTRAINT uk_enroll_student_class UNIQUE (student_id, class_enrolled_id)
        )';
    END IF;

    -- lessons
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'LESSONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE lessons (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR2(200) NOT NULL,
            description CLOB NOT NULL,
            "ORDER" NUMBER DEFAULT 0 NOT NULL,
            is_published NUMBER(1) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            class_lesson_id NUMBER NOT NULL,
            CONSTRAINT fk_lesson_class FOREIGN KEY (class_lesson_id) REFERENCES classes(id) ON DELETE CASCADE
        )';
    END IF;

    -- lesson_files
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'LESSON_FILES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE lesson_files (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            file VARCHAR2(100) NOT NULL,
            file_name VARCHAR2(255) NOT NULL,
            file_size NUMBER NOT NULL,
            uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            lesson_id NUMBER NOT NULL,
            CONSTRAINT fk_file_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE
        )';
    END IF;

    -- assignments
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'ASSIGNMENTS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE assignments (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR2(200) NOT NULL,
            description CLOB NOT NULL,
            due_date TIMESTAMP WITH TIME ZONE NOT NULL,
            max_points NUMBER DEFAULT 100 NOT NULL,
            allow_late_submission NUMBER(1) DEFAULT 1 NOT NULL,
            is_published NUMBER(1) DEFAULT 1 NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            class_assignment_id NUMBER NOT NULL,
            CONSTRAINT fk_assign_class FOREIGN KEY (class_assignment_id) REFERENCES classes(id) ON DELETE CASCADE
        )';
    END IF;

    -- submissions
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'SUBMISSIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE submissions (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            file VARCHAR2(100) NOT NULL,
            file_name VARCHAR2(255) NOT NULL,
            submitted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            status VARCHAR2(10) NOT NULL,
            points NUMBER,
            feedback CLOB,
            assignment_id NUMBER NOT NULL,
            student_id NUMBER NOT NULL,
            CONSTRAINT fk_sub_assign FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE CASCADE,
            CONSTRAINT fk_sub_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
            CONSTRAINT uk_sub_student_assign UNIQUE (assignment_id, student_id)
        )';
    END IF;

    -- questions
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'QUESTIONS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE questions (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question_text CLOB NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            lesson_id NUMBER NOT NULL,
            student_id NUMBER NOT NULL,
            CONSTRAINT fk_ques_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE,
            CONSTRAINT fk_ques_student FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
        )';
    END IF;

    -- answers
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'ANSWERS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE answers (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            answer_text CLOB NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            question_id NUMBER UNIQUE NOT NULL,
            teacher_id NUMBER NOT NULL,
            CONSTRAINT fk_ans_ques FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
            CONSTRAINT fk_ans_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE
        )';
    END IF;

    -- announcements
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'ANNOUNCEMENTS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE announcements (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR2(200) NOT NULL,
            content CLOB NOT NULL,
            is_pinned NUMBER(1) DEFAULT 0 NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            class_announcement_id NUMBER NOT NULL,
            teacher_id NUMBER NOT NULL,
            CONSTRAINT fk_ann_class FOREIGN KEY (class_announcement_id) REFERENCES classes(id) ON DELETE CASCADE,
            CONSTRAINT fk_ann_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE
        )';
    END IF;

    -- 3. Django Metadata/Sessions/Logs

    -- django_session
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'DJANGO_SESSION';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE django_session (
            session_key VARCHAR2(40) PRIMARY KEY,
            session_data CLOB NOT NULL,
            expire_date TIMESTAMP WITH TIME ZONE NOT NULL
        )';
    END IF;

    -- django_admin_log
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'DJANGO_ADMIN_LOG';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE django_admin_log (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            action_time TIMESTAMP WITH TIME ZONE NOT NULL,
            object_id CLOB,
            object_repr VARCHAR2(200) NOT NULL,
            action_flag NUMBER(2) NOT NULL,
            change_message CLOB NOT NULL,
            content_type_id NUMBER,
            user_id NUMBER NOT NULL,
            CONSTRAINT fk_admin_log_ct FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) ON DELETE SET NULL,
            CONSTRAINT fk_admin_log_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )';
    END IF;

    -- Register existing migrations to bypass Django's engine
    DELETE FROM django_migrations WHERE app IN ('admin', 'auth', 'contenttypes', 'sessions', 'core');
    INSERT INTO django_migrations (app, name, applied) VALUES ('contenttypes', '0001_initial', CURRENT_TIMESTAMP);
    INSERT INTO django_migrations (app, name, applied) VALUES ('contenttypes', '0002_remove_content_type_name', CURRENT_TIMESTAMP);
    INSERT INTO django_migrations (app, name, applied) VALUES ('auth', '0001_initial', CURRENT_TIMESTAMP);
    INSERT INTO django_migrations (app, name, applied) VALUES ('auth', '0012_alter_user_first_name_max_length', CURRENT_TIMESTAMP);
    INSERT INTO django_migrations (app, name, applied) VALUES ('core', '0001_initial', CURRENT_TIMESTAMP);
    INSERT INTO django_migrations (app, name, applied) VALUES ('admin', '0001_initial', CURRENT_TIMESTAMP);
    INSERT INTO django_migrations (app, name, applied) VALUES ('sessions', '0001_initial', CURRENT_TIMESTAMP);

END;
"""


    user = os.getenv('ORACLE_DB_USER', 'system')
    password = os.getenv('ORACLE_DB_PASSWORD', 'oracle')
    
    host = os.getenv('ORACLE_DB_HOST', 'localhost')
    port = os.getenv('ORACLE_DB_PORT', '1521')
    name = os.getenv('ORACLE_DB_NAME', 'XE')
    
    dsn = f"//{host}:{port}/{name}"


    try:
        connection = oracledb.connect(user=user, password=password, dsn=dsn)
        cursor = connection.cursor()
        
        print("Applying PL/SQL schema...")
        
        # In this embedded version, we have one big block.
        # However, we still split by / just in case multiple blocks are added later.
        statements = [s.strip() for s in SCHEMA_SQL.split('/') if s.strip()]
        
        for statement in statements:
            try:
                cursor.execute(statement)
            except Exception as e:
                print(f"Error executing statement: {e}")
                print(f"Statement: {statement[:100]}...")
                raise e
        
        connection.commit()
        print("Schema applied successfully.")
        
    except Exception as e:
        print(f"Error applying schema: {e}")
        sys.exit(1)
    finally:
        if 'connection' in locals():
            connection.close()



if __name__ == "__main__":
    apply_schema()
