-- ============================================================================
-- Smart Class Companion - Oracle Database Schema
-- ============================================================================
-- All database logic in pure PL/SQL
-- No Python code defines the schema - only this file

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;
BEGIN
    -- Drop existing tables in correct order
    FOR t IN (SELECT table_name FROM user_tables 
              WHERE table_name IN ('DJANGO_ADMIN_LOG', 'DJANGO_SESSION', 'ANNOUNCEMENTS', 
                                   'ANSWERS', 'QUESTIONS', 'SUBMISSIONS', 'ASSIGNMENTS', 
                                   'LESSON_FILES', 'LESSONS', 'ENROLLMENTS', 'CLASSES',
                                   'USERS_USER_PERMISSIONS', 'USERS_GROUPS', 'USERS',
                                   'AUTH_GROUP_PERMISSIONS', 'AUTH_GROUP', 'AUTH_PERMISSION',
                                   'DJANGO_CONTENT_TYPE', 'DJANGO_MIGRATIONS')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
        DBMS_OUTPUT.PUT_LINE('Dropped table: ' || t.table_name);
    END LOOP;
    
    -- ========================================================================
    -- DJANGO INTERNAL TABLES
    -- ========================================================================
    
    -- Migration tracking
    EXECUTE IMMEDIATE 'CREATE TABLE django_migrations (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        app VARCHAR2(255) NOT NULL,
        name VARCHAR2(255) NOT NULL,
        applied TIMESTAMP NOT NULL
    )';
    DBMS_OUTPUT.PUT_LINE('Created: django_migrations');
    
    -- Content type registry
    EXECUTE IMMEDIATE 'CREATE TABLE django_content_type (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100),
        app_label VARCHAR2(100) NOT NULL,
        model VARCHAR2(100) NOT NULL,
        CONSTRAINT uk_ct_label_model UNIQUE (app_label, model)
    )';
    DBMS_OUTPUT.PUT_LINE('Created: django_content_type');
    
    -- Permissions
    EXECUTE IMMEDIATE 'CREATE TABLE auth_permission (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255) NOT NULL,
        content_type_id NUMBER NOT NULL,
        codename VARCHAR2(100) NOT NULL,
        CONSTRAINT fk_perm_ct FOREIGN KEY (content_type_id) 
            REFERENCES django_content_type(id) ON DELETE CASCADE,
        CONSTRAINT uk_perm_ct_code UNIQUE (content_type_id, codename)
    )';
    DBMS_OUTPUT.PUT_LINE('Created: auth_permission');
    
    -- Groups
    EXECUTE IMMEDIATE 'CREATE TABLE auth_group (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(150) UNIQUE NOT NULL
    )';
    DBMS_OUTPUT.PUT_LINE('Created: auth_group');
    
    -- Group permissions
    EXECUTE IMMEDIATE 'CREATE TABLE auth_group_permissions (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        group_id NUMBER NOT NULL,
        permission_id NUMBER NOT NULL,
        CONSTRAINT fk_gp_group FOREIGN KEY (group_id) 
            REFERENCES auth_group(id) ON DELETE CASCADE,
        CONSTRAINT fk_gp_perm FOREIGN KEY (permission_id) 
            REFERENCES auth_permission(id) ON DELETE CASCADE,
        CONSTRAINT uk_gp_group_perm UNIQUE (group_id, permission_id)
    )';
    DBMS_OUTPUT.PUT_LINE('Created: auth_group_permissions');
    
    -- ========================================================================
    -- APPLICATION TABLES
    -- ========================================================================
    
    -- Users
    EXECUTE IMMEDIATE 'CREATE TABLE users (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        password VARCHAR2(128) NOT NULL,
        last_login TIMESTAMP,
        is_superuser NUMBER(1) DEFAULT 0 NOT NULL,
        username VARCHAR2(150) UNIQUE NOT NULL,
        first_name VARCHAR2(150),
        last_name VARCHAR2(150),
        email VARCHAR2(254),
        is_staff NUMBER(1) DEFAULT 0 NOT NULL,
        is_active NUMBER(1) DEFAULT 1 NOT NULL,
        date_joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        role VARCHAR2(10) NOT NULL,
        bio CLOB,
        avatar VARCHAR2(100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )';
    DBMS_OUTPUT.PUT_LINE('Created: users');
    
    -- User groups
    EXECUTE IMMEDIATE 'CREATE TABLE users_groups (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL,
        group_id NUMBER NOT NULL,
        CONSTRAINT fk_ug_user FOREIGN KEY (user_id) 
            REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT fk_ug_group FOREIGN KEY (group_id) 
            REFERENCES auth_group(id) ON DELETE CASCADE,
        CONSTRAINT uk_ug_user_group UNIQUE (user_id, group_id)
    )';
    DBMS_OUTPUT.PUT_LINE('Created: users_groups');
    
    -- User permissions
    EXECUTE IMMEDIATE 'CREATE TABLE users_user_permissions (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL,
        permission_id NUMBER NOT NULL,
        CONSTRAINT fk_uup_user FOREIGN KEY (user_id) 
            REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT fk_uup_perm FOREIGN KEY (permission_id) 
            REFERENCES auth_permission(id) ON DELETE CASCADE,
        CONSTRAINT uk_uup_user_perm UNIQUE (user_id, permission_id)
    )';
    DBMS_OUTPUT.PUT_LINE('Created: users_user_permissions');
    
    -- Classes
    EXECUTE IMMEDIATE 'CREATE TABLE classes (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(200) NOT NULL,
        description CLOB,
        class_code VARCHAR2(10) UNIQUE NOT NULL,
        subject VARCHAR2(100),
        room VARCHAR2(50),
        is_active NUMBER(1) DEFAULT 1 NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        teacher_id NUMBER NOT NULL,
        CONSTRAINT fk_classes_teacher FOREIGN KEY (teacher_id) 
            REFERENCES users(id) ON DELETE CASCADE
    )';
    DBMS_OUTPUT.PUT_LINE('Created: classes');
    
    -- Enrollments
    EXECUTE IMMEDIATE 'CREATE TABLE enrollments (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        is_active NUMBER(1) DEFAULT 1 NOT NULL,
        class_enrolled_id NUMBER NOT NULL,
        student_id NUMBER NOT NULL,
        CONSTRAINT fk_enroll_class FOREIGN KEY (class_enrolled_id) 
            REFERENCES classes(id) ON DELETE CASCADE,
        CONSTRAINT fk_enroll_student FOREIGN KEY (student_id) 
            REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT uk_enroll_student_class UNIQUE (student_id, class_enrolled_id)
    )';
    DBMS_OUTPUT.PUT_LINE('Created: enrollments');
    
    -- Lessons
    EXECUTE IMMEDIATE 'CREATE TABLE lessons (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR2(200) NOT NULL,
        description CLOB NOT NULL,
        "ORDER" NUMBER DEFAULT 0 NOT NULL,
        is_published NUMBER(1) DEFAULT 1 NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        class_lesson_id NUMBER NOT NULL,
        CONSTRAINT fk_lesson_class FOREIGN KEY (class_lesson_id) 
            REFERENCES classes(id) ON DELETE CASCADE
    )';
    DBMS_OUTPUT.PUT_LINE('Created: lessons');
    
    -- Lesson files
    EXECUTE IMMEDIATE 'CREATE TABLE lesson_files (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "FILE" VARCHAR2(100) NOT NULL,
        file_name VARCHAR2(255) NOT NULL,
        file_size NUMBER NOT NULL,
        uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        lesson_id NUMBER NOT NULL,
        CONSTRAINT fk_file_lesson FOREIGN KEY (lesson_id) 
            REFERENCES lessons(id) ON DELETE CASCADE
    )';
    DBMS_OUTPUT.PUT_LINE('Created: lesson_files');
    
    -- Assignments
    EXECUTE IMMEDIATE 'CREATE TABLE assignments (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR2(200) NOT NULL,
        description CLOB NOT NULL,
        due_date TIMESTAMP NOT NULL,
        max_points NUMBER DEFAULT 100 NOT NULL,
        allow_late_submission NUMBER(1) DEFAULT 1 NOT NULL,
        is_published NUMBER(1) DEFAULT 1 NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        class_assignment_id NUMBER NOT NULL,
        CONSTRAINT fk_assign_class FOREIGN KEY (class_assignment_id) 
            REFERENCES classes(id) ON DELETE CASCADE
    )';
    DBMS_OUTPUT.PUT_LINE('Created: assignments');
    
    -- Submissions
    EXECUTE IMMEDIATE 'CREATE TABLE submissions (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "FILE" VARCHAR2(100) NOT NULL,
        file_name VARCHAR2(255) NOT NULL,
        submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        status VARCHAR2(10) NOT NULL,
        points NUMBER,
        feedback CLOB,
        assignment_id NUMBER NOT NULL,
        student_id NUMBER NOT NULL,
        CONSTRAINT fk_sub_assign FOREIGN KEY (assignment_id) 
            REFERENCES assignments(id) ON DELETE CASCADE,
        CONSTRAINT fk_sub_student FOREIGN KEY (student_id) 
            REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT uk_sub_student_assign UNIQUE (assignment_id, student_id)
    )';
    DBMS_OUTPUT.PUT_LINE('Created: submissions');
    
    -- Questions
    EXECUTE IMMEDIATE 'CREATE TABLE questions (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        question_text CLOB NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        lesson_id NUMBER NOT NULL,
        student_id NUMBER NOT NULL,
        CONSTRAINT fk_ques_lesson FOREIGN KEY (lesson_id) 
            REFERENCES lessons(id) ON DELETE CASCADE,
        CONSTRAINT fk_ques_student FOREIGN KEY (student_id) 
            REFERENCES users(id) ON DELETE CASCADE
    )';
    DBMS_OUTPUT.PUT_LINE('Created: questions');
    
    -- Answers
    EXECUTE IMMEDIATE 'CREATE TABLE answers (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        answer_text CLOB NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        question_id NUMBER UNIQUE NOT NULL,
        teacher_id NUMBER NOT NULL,
        CONSTRAINT fk_ans_ques FOREIGN KEY (question_id) 
            REFERENCES questions(id) ON DELETE CASCADE,
        CONSTRAINT fk_ans_teacher FOREIGN KEY (teacher_id) 
            REFERENCES users(id) ON DELETE CASCADE
    )';
    DBMS_OUTPUT.PUT_LINE('Created: answers');
    
    -- Announcements
    EXECUTE IMMEDIATE 'CREATE TABLE announcements (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR2(200) NOT NULL,
        content CLOB NOT NULL,
        is_pinned NUMBER(1) DEFAULT 0 NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        class_announcement_id NUMBER NOT NULL,
        teacher_id NUMBER NOT NULL,
        CONSTRAINT fk_ann_class FOREIGN KEY (class_announcement_id) 
            REFERENCES classes(id) ON DELETE CASCADE,
        CONSTRAINT fk_ann_teacher FOREIGN KEY (teacher_id) 
            REFERENCES users(id) ON DELETE CASCADE
    )';
    DBMS_OUTPUT.PUT_LINE('Created: announcements');
    
    -- ========================================================================
    -- DJANGO METADATA TABLES
    -- ========================================================================
    
    -- Sessions
    EXECUTE IMMEDIATE 'CREATE TABLE django_session (
        session_key VARCHAR2(40) PRIMARY KEY,
        session_data CLOB NOT NULL,
        expire_date TIMESTAMP NOT NULL
    )';
    DBMS_OUTPUT.PUT_LINE('Created: django_session');
    
    -- Admin log
    EXECUTE IMMEDIATE 'CREATE TABLE django_admin_log (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        action_time TIMESTAMP NOT NULL,
        object_id CLOB,
        object_repr VARCHAR2(200) NOT NULL,
        action_flag NUMBER(2) NOT NULL,
        change_message CLOB NOT NULL,
        content_type_id NUMBER,
        user_id NUMBER NOT NULL,
        CONSTRAINT fk_admin_log_ct FOREIGN KEY (content_type_id) 
            REFERENCES django_content_type(id) ON DELETE SET NULL,
        CONSTRAINT fk_admin_log_user FOREIGN KEY (user_id) 
            REFERENCES users(id) ON DELETE CASCADE
    )';
    DBMS_OUTPUT.PUT_LINE('Created: django_admin_log');
    
    -- ========================================================================
    -- REGISTER DJANGO MIGRATIONS
    -- ========================================================================
    
    EXECUTE IMMEDIATE 'INSERT INTO django_migrations (app, name, applied) 
        VALUES (''contenttypes'', ''0001_initial'', CURRENT_TIMESTAMP)';
    
    EXECUTE IMMEDIATE 'INSERT INTO django_migrations (app, name, applied) 
        VALUES (''contenttypes'', ''0002_remove_content_type_name'', CURRENT_TIMESTAMP)';
    
    EXECUTE IMMEDIATE 'INSERT INTO django_migrations (app, name, applied) 
        VALUES (''auth'', ''0001_initial'', CURRENT_TIMESTAMP)';
    
    EXECUTE IMMEDIATE 'INSERT INTO django_migrations (app, name, applied) 
        VALUES (''auth'', ''0012_alter_user_first_name_max_length'', CURRENT_TIMESTAMP)';
    
    EXECUTE IMMEDIATE 'INSERT INTO django_migrations (app, name, applied) 
        VALUES (''core'', ''0001_initial'', CURRENT_TIMESTAMP)';
    
    EXECUTE IMMEDIATE 'INSERT INTO django_migrations (app, name, applied) 
        VALUES (''admin'', ''0001_initial'', CURRENT_TIMESTAMP)';
    
    EXECUTE IMMEDIATE 'INSERT INTO django_migrations (app, name, applied) 
        VALUES (''sessions'', ''0001_initial'', CURRENT_TIMESTAMP)';
    
    COMMIT;

    
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('✓ Schema creation complete!');
    DBMS_OUTPUT.PUT_LINE('✓ All 19 tables created');
    DBMS_OUTPUT.PUT_LINE('✓ All migrations registered');
    
END;
/